to:
  image: schmunk42/nginx-redirect
  ports:
    - "8888:80"
  environment:
    - SERVER_REDIRECT=www.example.com
    # optionally define path to redirect all requests
    # if not set nginx var $request_uri is used
    #- SERVER_REDIRECT_PATH=/landingpage
    # optionally define schema to redirect all requests
    # if not set nginx var $scheme is used
    #- SERVER_REDIRECT_SCHEME=https
